apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knudon-ingress
  namespace: knudon
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - rajarshibhattacharya.in         
    secretName: knudon-tls-secret
  rules:
  - host: rajarshibhattacharya.in     
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: knudon-backend
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: knudon-frontend
            port:
              number: 80
